pep_config: analysis.configuration.yaml
output_dir: results
pipeline_interfaces:
   - /store24/project24/becgsc_001/coding/NGS.analysis.v3/sample_pipeline_interface.yaml
   - /store24/project24/becgsc_001/coding/NGS.analysis.v3/project_pipeline_interface.yaml
pipestat:
  results_file_path: "{record_identifier}/stats.yaml"
  flag_file_dir: results/flags
